# WWW
[[redirects]]
from = "/www.hirechrisfinazzo.com"
to = "/hirechrisfinazzo.com"
status = 301
force = false
# Netlify
[[redirects]]
from = "/https://gracious-babbage-21fe68.netlify.com"
to = "/hirechrisfinazzo.com"
status = 301
force = false
# Routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
# Plugins
[[plugins]]
package = "netlify-plugin-csp-generator"
  [plugins.inputs]
  buildDir = "build"
  [plugins.inputs.policies]
    defaultSrc = "'none'"
    fontSrc = "'self'"
    imgSrc = "'self'"
    styleSrc = "'self' https://use.fontawesome.com"
    scriptSrc = "'self'"
    baseUri = "'self'"
    connectSrc = "'self'"
    objectSrc = "'none'"
    formAction = "'self'"
    frameAncestors = "'none'"
    workerSrc = "'self'"

[[headers]]
  for = "/*"
  [headers.values]  
    cache-control = '''
    no-transform'''
    Upgrade-Insecure-Requests = "1"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

